import { FormEvent, useEffect, useState } from 'react'; import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'; import { api, GameClass, Raid, Result } from './api';

const glyphs:Record<string,string>={smith:'⚒',mage:'✦',poet:'❧',knight:'♜',druid:'☘',alchemist:'⚗'};
export function App(){
 const queryClient=useQueryClient(); const [logged,setLogged]=useState(api.hasSession()); const [error,setError]=useState('');
 useEffect(()=>{if(!logged&&window.WebApp?.initData){api.loginMax(window.WebApp.initData).then(()=>setLogged(true)).catch(e=>setError(e.message));}},[logged]);
 const me=useQuery({queryKey:['me'],queryFn:api.me,enabled:logged});
 if(!logged)return <Login error={error} onDone={()=>setLogged(true)}/>;
 if(me.isLoading)return <Shell><p className="eyebrow">Разжигаем очаг…</p><div className="skeleton"/></Shell>;
 if(me.error)return <Shell><p className="error">{me.error.message}</p><button onClick={()=>{api.logout();setLogged(false)}}>Войти заново</button></Shell>;
 if(!me.data?.character)return <CreateHero onDone={()=>queryClient.invalidateQueries({queryKey:['me']})}/>;
 return <Home data={me.data} refresh={()=>queryClient.invalidateQueries({queryKey:['me']})}/>;
}
function Shell({children}:{children:React.ReactNode}){return <main><header><span className="brand-mark">К</span><div><b>КРАДА</b><small>хроники живого огня</small></div></header>{children}</main>}
function Login({onDone,error}:{onDone:()=>void;error:string}){const [name,setName]=useState('Добрыня');const login=useMutation({mutationFn:()=>api.login(name),onSuccess:onDone});return <Shell><section className="hero"><span className="rune">ᛟ</span><p className="eyebrow">Образовательная RPG</p><h1>Зажги огонь<br/><i>знаний</i></h1><p>Войди в земли Крады, собери героя и одолей тени невежества.</p></section><form onSubmit={e=>{e.preventDefault();login.mutate()}}><label>Имя странника<input value={name} onChange={e=>setName(e.target.value)} minLength={2}/></label><button disabled={login.isPending}>Войти в летопись <span>→</span></button>{(error||login.error)&&<p className="error">{error||login.error?.message}</p>}<small className="hint">Локальный режим · MAX подключится автоматически внутри приложения</small></form></Shell>}
function CreateHero({onDone}:{onDone:()=>void}){const classes=useQuery({queryKey:['classes'],queryFn:api.classes});const [chosen,setChosen]=useState('mage');const [name,setName]=useState('Ратибор');const create=useMutation({mutationFn:()=>api.createCharacter(name,chosen),onSuccess:onDone});return <Shell><p className="eyebrow">Шаг I · Призвание</p><h1>Кем ты станешь?</h1><p className="muted">Выбор меняет стиль приключений, но не силу твоих знаний.</p><div className="class-grid">{classes.data?.map((c:GameClass)=><button type="button" className={`class-card ${chosen===c.key?'selected':''}`} onClick={()=>setChosen(c.key)} key={c.key}><span>{glyphs[c.key]}</span><b>{c.title}</b><small>{c.description}</small></button>)}</div><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate()}}><label>Имя героя<input value={name} onChange={e=>setName(e.target.value)}/></label><button>Принять призвание</button></form></Shell>}
function Home({data,refresh}:{data:Awaited<ReturnType<typeof api.me>>;refresh:()=>void}){const [raid,setRaid]=useState<Raid|null>(null);const [result,setResult]=useState<Result|null>(null);const start=useMutation({mutationFn:api.startRaid,onSuccess:r=>{setRaid(r);setResult(null)}});const answer=useMutation({mutationFn:(value:string)=>api.answer(raid!.id,value),onSuccess:r=>{setResult(r);setRaid(null);refresh()}});const c=data.character!;return <Shell><section className="profile"><div className="avatar"><span>{glyphs[c.class_key]}</span></div><div><p className="eyebrow">{data.school_name} · {data.class_name}</p><h2>{c.name}</h2><p>Уровень {c.level} · {c.xp} опыта</p></div></section><div className="stats"><article><small>Искры</small><strong>◆ {data.embers}</strong></article><article><small>Слава школы</small><strong>{data.school_score}</strong></article></div>{raid?<RaidView raid={raid} pending={answer.isPending} answer={v=>answer.mutate(v)}/>:result?<ResultView result={result} again={()=>start.mutate()}/>:<section className="quest"><p className="eyebrow">Доступное испытание</p><h2>Тень над древней летописью</h2><p>История · одно испытание · награда до 15 искр</p><button onClick={()=>start.mutate()} disabled={start.isPending}>Начать рейд <span>⚔</span></button></section>}<nav><span className="active">⌂<small>Очаг</small></span><span>♜<small>Рейтинг</small></span><span>☷<small>Сумка</small></span></nav></Shell>}
function RaidView({raid,answer,pending}:{raid:Raid;answer:(v:string)=>void;pending:boolean}){return <section className="quest raid"><p className="eyebrow">{raid.question.subject} · испытание I</p><h2>{raid.question.text}</h2><div className="answers">{raid.question.options.map(v=><button disabled={pending} key={v} onClick={()=>answer(v)}>{v}</button>)}</div></section>}
function ResultView({result,again}:{result:Result;again:()=>void}){return <section className={`quest result ${result.correct?'win':''}`}><span className="result-rune">{result.correct?'✦':'☾'}</span><p className="eyebrow">Рейд завершён</p><h2>{result.correct?'Летопись спасена':'Знание крепнет'}</h2><p>{result.explanation}</p><div className="reward"><b>+{result.xp_awarded} опыта</b><b>+{result.embers_awarded} ◆</b></div><button onClick={again}>Новое испытание</button></section>}
